[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
marketplace = "7QBSkFhooeYTXKcHQxa7HjRGC7vnmkX1TXhBZdbwHsoJ"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
